import Head from 'next/head';
import { signIn, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Index() {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === 'authenticated') {
      router.push('/dashboard');
    }
  }, [router, status]);

  const content = (() => {
    if (status === 'loading') {
      return <h1>Loading...</h1>;
    }

    if (session?.error || status === 'unauthenticated') {
      return <button onClick={() => signIn('github')}>Sign in</button>;
    }

    return null;
  })();

  return <div>
    <Head>
      <title>MyGymPal</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    {content}
  </div>;
}
