import cn from 'classnames';
import Button from 'components/Button';
import { signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import styles from './index.module.scss';

export default function Page() {
  const { data: session } = useSession();

  const greeting = session?.user ? `Welcome ${session.user.name}!` : 'Welcome stranger!';

  return (
    <>
      <Head>
        <title>MyGymPal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={cn(styles.main, 'bg-slate-800 text-white')}>
        <h1 className="text-center text-5xl text-sky-50 mb-0 pb-3">MyGymPal</h1>
        <p className="font-medium pb-3">{greeting}</p>
        <Button onClick={() => signOut()}>Sign out</Button>
      </main>
    </>
  );
}
