import cn from 'classnames';
import { Button } from 'components/Button';
import { signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import styles from './Index.module.scss';

const Dashboard = () => {
  const { data: session } = useSession();

  const greeting = session?.user
    ? `Welcome ${session.user.name}!`
    : 'Welcome stranger!';

  return <div className={styles.container}>
    <Head>
      <title>MyGymPal</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={cn(styles.main, 'bg-slate-800 text-white')}>
      <h1 className={cn(styles.title, 'text-5xl text-sky-50 pb-3')}>MyGymPal</h1>
      <p className={cn('font-medium pb-3')}>{greeting}</p>
      <Button onClick={() => signOut()}>Sign out</Button>
    </main>
  </div>;
};

export default Dashboard;
