import cn from 'classnames';
import { signOut } from 'next-auth/react';
import Head from 'next/head';
import styles from './Index.module.scss';

const Dashboard = () => <div className={styles.container}>
  <Head>
    <title>MyGymPal</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={cn(styles.main, 'bg-slate-800')}>
    <h1 className={cn(styles.title, 'text-xl text-sky-500')}>MyGymPal</h1>
    <button onClick={() => signOut()}>Sign out</button>;
  </main>
</div>;

export default Dashboard;
