import { Prisma } from '@prisma/client';
import cn from 'classnames';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import styles from './Index.module.scss';

interface IndexProps {
  user: Prisma.UserGetPayload<{}>;
}

export default function Index({ user }: IndexProps) {
  console.log(user);

  return (
    <div className={styles.container}>
      <Head>
        <title>MyGymPal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={cn(styles.main, "bg-slate-800")}>
        <h1 className={cn(styles.title, "text-xl text-sky-500")}>MyGymPal</h1>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const {prisma} = await import('@/utils/prisma');

  let user = await prisma.user.findFirst({ where: { name: 'Ottigan' } });

  if (!user) {
    user =  await prisma.user.create({ data: { name: 'Ottigan', surname: 'Gottry' } });
  }

  return {
    props: {
      user,
    },
  };
};
