import { WorkoutExercise } from '@prisma/client';
import Button from 'components/Button';
import Input from 'components/Input';
import Modal from 'components/Modal';
import useFetch from 'hooks/useFetch';
import useModal from 'hooks/useModal';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { authOptions, UserWithId } from 'pages/api/auth/[...nextauth].next';
import { ChangeEvent, FormEvent, useCallback, useEffect, useReducer, useState } from 'react';
import { WorkoutWithExercises } from 'types';
import { getServerSession } from 'utils/auth';
import { db } from 'utils/db';
import WorkoutExercises from './components/WorkoutExercises';
import Workouts from './components/Workouts';
import { formDataTemplate, getTemplate, reducer } from './utils';

interface WorkoutsProps {
  workouts: WorkoutWithExercises[];
}

export default function Page(props: WorkoutsProps) {
  const [workouts, setWorkouts] = useState(props.workouts);
  const [formData, handleFormData] = useReducer(reducer, formDataTemplate);
  const [exercises, setExercises] = useState<WorkoutExercise[]>([getTemplate()]);
  const [isModalVisible, handleModalVisibility] = useModal();
  const [modalType, setModalType] = useState<'create' | 'update'>('create');
  const workoutController = useFetch<WorkoutWithExercises[]>();

  const handleChange = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    const { target: { value: payload, name } } = e;

    handleFormData({ type: name, payload });
  }, []);

  const handleView = useCallback((payload: WorkoutWithExercises) => {
    handleFormData({ type: 'set', payload });
    setExercises(payload.exercises);
    setModalType('update');
    handleModalVisibility();
  }, [handleModalVisibility]);

  const handleWorkoutExercises = useCallback((payload: WorkoutExercise[]) => {
    handleFormData({ type: 'exercises', payload });
  }, []);

  const handleCreate = useCallback((e: FormEvent) => {
    e.preventDefault();

    workoutController.exec({
      url: '/api/workouts',
      options: {
        method: 'POST',
        body: JSON.stringify(formData),
      },
      onSucess: () => {
        handleFormData({ type: 'clear' });
        handleModalVisibility();
      },
    });
  }, [formData, handleModalVisibility, workoutController]);

  const handleUpdate = useCallback((e: FormEvent) => {
    e.preventDefault();

    workoutController.exec({
      url: '/api/workouts',
      options: {
        method: 'PATCH',
        body: JSON.stringify(formData),
      },
      onSucess: () => {
        handleFormData({ type: 'clear' });
        handleModalVisibility();
      },
    });
  }, [formData, handleModalVisibility, workoutController]);

  const handleDelete = useCallback((id: string) => workoutController.exec({
    url: `/api/workouts?id=${id}`,
    options: {
      method: 'DELETE',
    },
  }), [workoutController]);

  useEffect(() => {
    if (workoutController.data) {
      setWorkouts(workoutController.data);
    }
  }, [workoutController.data]);

  return (
    <>
      <Head>
        <title>MyGymPal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-3">
        <Button
          onClick={() => {
            setModalType('create');
            handleFormData({ type: 'clear' });
            setExercises([getTemplate()]);
            handleModalVisibility();
          }}
          disabled={workoutController.isLoading}
          className="basis-4/12 mb-3"
        >
          Create
        </Button>
        <Modal isVisible={isModalVisible} visibilityHandler={handleModalVisibility}>
          <form className="flex flex-wrap gap-2 mb-9" autoComplete="off">
            <Input
              onChange={handleChange}
              value={formData.name}
              label="Name"
              name="name"
            />
            <WorkoutExercises exercises={exercises} onChange={handleWorkoutExercises} />
            {modalType === 'create'
              ? (
                <Button
                  onClick={handleCreate}
                  type="submit"
                  disabled={workoutController.isLoading}
                  className="basis-4/12"
                >
                  Create
                </Button>
              )
              : (
                <Button
                  onClick={handleUpdate}
                  type="submit"
                  disabled={workoutController.isLoading}
                  className="basis-4/12"
                >
                  Update
                </Button>
              )}
          </form>
        </Modal>
        <Workouts
          isLoading={workoutController.isLoading}
          workouts={workouts}
          handleView={handleView}
          handleDelete={handleDelete}
        />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  const workouts: WorkoutWithExercises[] = await db.workout.findMany({
    where: { userId: (session?.user as UserWithId).id },
    include: { exercises: true },
  });

  return { props: { workouts } };
};
